### ISSUE TITLE
can't install in vscode

### ISSUE THREAD

**Issue by Notenlish** [stef-levesque/vscode-shader#72]
```
2024-06-29 13:05:37.363 [error] Cannot read properties of undefined (reading 'accessToken'): TypeError: Cannot read properties of undefined (reading 'accessToken')
    at b.h (vscode-file://vscode-app/c:/Users/%C4%B0hsan/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1693:21270)
    at b.j (vscode-file://vscode-app/c:/Users/%C4%B0hsan/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1693:22006)
    at u.value (vscode-file://vscode-app/c:/Users/%C4%B0hsan/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1693:21027)
2024-06-29 13:05:48.263 [error] Error: Unable to read file 'c:\Users\İhsan\.vscode\extensions\slevesque.shader-1.1.5\package.json' (Error: Unable to resolve nonexistent file 'c:\Users\İhsan\.vscode\extensions\slevesque.shader-1.1.5\package.json')
    at $.F (c:\Users\İhsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:58:19188)
    at $.D (c:\Users\İhsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:58:18983)
    at async $.C (c:\Users\İhsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:58:18295)
    at async m.updateMetadata (c:\Users\İhsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:104:85609)
    at async W.extractUserExtension (c:\Users\İhsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:104:110691)
    at async ie.u (c:\Users\İhsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:104:117704)
    at async ie.C (c:\Users\İhsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:104:120237)
    at async ie.x (c:\Users\İhsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:104:119541)
    at async ie.h (c:\Users\İhsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:104:117226)
2024-06-29 13:05:48.308 [error] Unable to read file 'c:\Users\İhsan\.vscode\extensions\slevesque.shader-1.1.5\package.json' (Error: Unable to resolve nonexistent file 'c:\Users\İhsan\.vscode\extensions\slevesque.shader-1.1.5\package.json'): Error: Unable to read file 'c:\Users\İhsan\.vscode\extensions\slevesque.shader-1.1.5\package.json' (Error: Unable to resolve nonexistent file 'c:\Users\İhsan\.vscode\extensions\slevesque.shader-1.1.5\package.json')
    at $.F (c:\Users\İhsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:58:19188)
    at $.D (c:\Users\İhsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:58:18983)
    at async $.C (c:\Users\İhsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:58:18295)
    at async m.updateMetadata (c:\Users\İhsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:104:85609)
    at async W.extractUserExtension (c:\Users\İhsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:104:110691)
    at async ie.u (c:\Users\İhsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:104:117704)
    at async ie.C (c:\Users\İhsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:104:120237)
    at async ie.x (c:\Users\İhsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:104:119541)
    at async ie.h (c:\Users\İhsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:104:117226)
```

Version: 1.88.1 (user setup)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:41:02.734Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by Notenlish** [comment]
I think the problem is here: `(Error: Unable to resolve nonexistent file 'c:\Users\İhsan\.vscode\extensions\slevesque.shader-1.1.5\package.json'): Error: Unable to read file 'c:\Users\İhsan\.vscode\extensions\slevesque.shader-1.1.5\package.json' (Error: Unable to resolve nonexistent file 'c:\Users\İhsan\.vscode\extensions\slevesque.shader-1.1.5\package.json')`
